### ISSUE TITLE
[Feature] : Document the "package-to-scan" property

### ISSUE THREAD

**Issue by TristanVajente** [societe-generale/failover#52]
## Is your feature request related to a problem? Please describe.

In the [documentation](https://societe-generale.github.io/failover/#/README), I didn't see a section related to the "package-to-scan" property  
This property is mandatory because it is used for the reflexions library, and currently the "mandatory" part is implicit 
When this property is missing, the Failover lib is not working silently

## Describe the solution you'd like

Documentation this mandatory parameter in the quick start section

## Describe alternatives you've considered

- Throw an error on startup when the property is missing
- Throw an error in the ```DefaultFailoverScanner::init``` method when ```Reflexions.getMethodsAnnotatedWith(Failover.class)``` return is empty (or log a warning ?)

I'd prefer having the property documented than creating issues for the following version upgrade !

## Which module is impacted

The documentation

## Additional context

Other idea : Add a dependency matrix between the failover-spring-boot-starter / spring-boot-starter / Java versions 
Due to the issue #40, I thought the 1.1.0 version (for spring-boot 2 if I understood correctly) wasn't compatible with Java 17.  
After testing, it looks to be working fine

**Comment by anandmnair** [comment]
Thank you @TristanVajente  for reporting the issue. 

I have fixed the documentation. 

Also saw your recommendation on validating the mandatory configurations. We will improve this area in the coming release.  

Fixed #53

**Comment by anandmnair** [comment]
If we miss the property package-to-scan , we had two place the impact : 
1. cache store
2. reporting : To have a dashboard with all failover details


To simplify this, I have removed the dependency on @Failover scanning from cache store.  So even if you miss the property, the failover will not fail ( in case of cache store ). So the only impact will be on the reporting. 

So in case if we miss the property , we can have a validation and log a warning. (so the property will be come the optional one in such cases ) 

Looking forward to see your feedback
